#!/bin/bash
cd  /home/gedgar
python3  passwords.py
cd new_python/code
#python3 -m redis_support_py3.load_files_py3
#python3 -m redis_support_py3.construct_graph_py3
#./process_control_py3.bsh&
cd lacima_web
./lacima_web.bsh&
cd ../


